"""add task_id column in video_file table

Revision ID: e2262720fca7
Revises: 5f0bbbf21058
Create Date: 2021-09-27 07:53:30.682430

"""

# revision identifiers, used by Alembic.
revision = 'e2262720fca7'
down_revision = '5f0bbbf21058'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_file', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_file', 'task_id')
    # ### end Alembic commands ###
